# name: Cypress Tests

# # env:
# #   MYSQL_DATABASE: datamundi
# #   MYSQL_USER: root
# #   MYSQL_PASSWORD: password
# #   MYSQL_HOST: 3306

# on: [push]

# jobs:
# phases:
#   install:
#     runtime-versions:
#       nodejs: 16
#     commands:
#       - npm install -g
#   build:
#     commands:
#       - npm
#       - npm dev
#       - npm start
#       - npm cy-run
# cache:
#   paths:
#     - "/node_modules/**/*"
# #   ci:
# #     runs-on: ubuntu-latest
# #     services:
# #       mysql-master:
# #         image: mysql:5.7
# #         ports:
# #           - 3306/tcp
# #         env:
# #           MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
# #           MYSQL_USER: ${{ env.MYSQL_USER }}
# #           MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
# #           MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
# #         options: >-
# #           --name=mysql-master
# #           --health-cmd="mysqladmin ping"
# #           --health-interval=10s
# #           --health-timeout=5s
# #           --health-retries=3
# #     steps:
# #       - uses: actions/checkout@v2
# #       - name: Install packages
# #         run: "npm ci"
# #       - name: Setup Database
# #         run: "npm run migrations"
# #       - name: Run Tests
# #         run: "npm run test"
# #   cypress-run:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout
# #         uses: actions/checkout@v3
# #       # Install NPM dependencies, cache them correctly
# #       # and run all Cypress tests
# #       - name: Setup Node
# #         uses: actions/setup-node@v1
# #         with:
# #           node-version: 14
# #       - name: Start server
# #         run: npm start &
# #         env:
# #           host: "localhost"
# #           user: "root"
# #           password: "password"
# #           port: "3306"
# #           database: "datamundi"
# #           decimalNumbers: true
# #       - name: Cypress run
# #         uses: cypress-io/github-action@v4.1.0 # use the explicit version number
# #         with:
# #           start: npm start
# #           wait-on: "http://localhost:3000"
# #           record: 9f870677-7267-472a-a069-bec59562e77f

name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: datamundi
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Wait for database
        run: npx wait-on tcp:localhost:3000 -t 30000
      - name: Migrate database
        env:
          NODE_ENV: test
          DATABASE_URL: mysql://root:root@localhost:3000/test
        run: npm run migrate
      - name: Run tests
        env:
          NODE_ENV: test
          DATABASE_URL: mysql://root:root@localhost:3000/test
        run: npm run test
