name: Cypress Tests

env:
  MYSQL_DATABASE: datamundi
  MYSQL_USER: root
  MYSQL_PASSWORD: password
  MYSQL_HOST: 3306

on: [push]

jobs:
  services:
    mysql-master:
      image: mysql:5.7
      ports:
        - 3306/tcp
      env:
        MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        MYSQL_USER: ${{ env.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
  steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: "npm ci"
    - name: Setup Database
      run: "npm run migrations"
    - name: Run Tests
      run: "npm run test"
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Start server
        run: npm start &
        env:
          host: "localhost"
          user: "root"
          password: "password"
          port: "3306"
          database: "datamundi"
          decimalNumbers: true
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0 # use the explicit version number
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          record: 9f870677-7267-472a-a069-bec59562e77f
