name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Start server
        run: |
        export DB_HOST=$(node -p "require('./config').db.host")
          export DB_USER=$(node -p "require('./config').db.user")
          export DB_PASSWORD=$(node -p "require('./config').db.password")
          export DB_PORT=$(node -p "require('./config').db.port")
          export DB_DATABASE=$(node -p "require('./config').db.database")
          export DB_DECIMAL_NUMBERS=$(node -p "require('./config').db.decimalNumbers")
        npm start &
      - name: Wait for server to start
        run: sleep 5
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0 # use the explicit version number
        with:
          record: 9f870677-7267-472a-a069-bec59562e77f
          start: npm start
          wait-on: "http://localhost:3000"
