name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Start server
        start: npm start
        wait-on: "http://localhost:3000"
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0 # use the explicit version number
        with:
          record: 9f870677-7267-472a-a069-bec59562e77f
          start: npm start
          wait-on: "http://localhost:3000"
